services:
  - type: web
    name: imdb-tmdb-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
